/* exporter.js — Folder structure + file writer */

async function exportInstrument(samples, stats, config, outputDir, onProgress) {
  var mapped = samples.filter(function(s) { return s.parsed; });
  var instrumentName = stats.instrument || 'Instrument';
  var basePath = outputDir + '/' + instrumentName + '_SampleArchitect';

  var stages = [
    'Creating folder structure',
    'Organizing samples',
    'Copying sample files',
    'Copying sample files',
    'Generating KSP script',
    'Writing KSP script',
    'Creating setup guide',
    'Finalizing'
  ];

  // Stage 1: Create folders
  onProgress(0, stages[0]);
  await window.__TAURI__.core.invoke('create_directory', { path: basePath + '/Samples' });
  await window.__TAURI__.core.invoke('create_directory', { path: basePath + '/Scripts' });

  // Create articulation subfolders
  var articulations = {};
  mapped.forEach(function(s) {
    if (s.articulation) articulations[s.articulation] = true;
  });
  var artList = Object.keys(articulations);
  for (var a = 0; a < artList.length; a++) {
    await window.__TAURI__.core.invoke('create_directory', {
      path: basePath + '/Samples/' + artList[a]
    });
  }

  // Stage 2-4: Copy samples
  onProgress(1, stages[1]);
  for (var i = 0; i < mapped.length; i++) {
    var s = mapped[i];
    var destFolder = s.articulation || 'Uncategorized';
    var destPath = basePath + '/Samples/' + destFolder + '/' + s.filename;

    var stageIdx = Math.min(3, 1 + Math.floor((i / mapped.length) * 3));
    onProgress(stageIdx, stages[stageIdx]);

    await window.__TAURI__.core.invoke('copy_file', {
      src: s.path,
      dest: destPath
    });
  }

  // Stage 5-6: Generate and write KSP
  onProgress(4, stages[4]);
  var kspScript = generateKSP(mapped, stats, config);

  onProgress(5, stages[5]);
  await window.__TAURI__.core.invoke('write_text_file', {
    path: basePath + '/Scripts/' + instrumentName + '.ksp',
    contents: kspScript
  });

  // Stage 7: Setup guide
  onProgress(6, stages[6]);
  var guide = generateSetupGuide(mapped, stats, config, basePath);
  await window.__TAURI__.core.invoke('write_text_file', {
    path: basePath + '/Setup Guide.txt',
    contents: guide
  });

  // Stage 8: Finalize
  onProgress(7, stages[7]);

  return basePath;
}

function generateSetupGuide(samples, stats, config, outputPath) {
  var instrumentName = stats.instrument || 'Instrument';
  var enabledCtrls = getEnabledControls().map(function(c) { return c.config.label; });
  var enabledFx = getEnabledEffects().map(function(f) { return f.config.label; });

  // Build sample map table
  var tableLines = [];
  samples.forEach(function(s) {
    if (!s.parsed) return;
    var noteName = formatNoteName(s.note, s.accidental, s.octave);
    tableLines.push(
      s.filename.padEnd(45) +
      noteName.padEnd(6) +
      ('v' + s.velocityLayer).padEnd(5) +
      ('rr' + s.roundRobin).padEnd(5) +
      (s.articulation || '')
    );
  });

  var guide = [
    '================================================================================',
    '  ' + instrumentName + ' — Loading Guide',
    '  Generated by SampleArchitect',
    '================================================================================',
    '',
    'LOADING INTO KONTAKT 6+',
    '========================',
    '',
    '1. Open Kontakt (standalone or as a plugin in your DAW)',
    '',
    '2. Click the "Files" tab in the left sidebar',
    '',
    '3. Navigate to this folder:',
    '   ' + outputPath,
    '',
    '4. Go to File > New Instrument (or right-click in the rack > New Instrument)',
    '',
    '5. Open the Mapping Editor:',
    '   - Click the wrench icon (Instrument Edit Mode)',
    '   - The Mapping Editor panel should be visible at the bottom',
    '',
    '6. Select all sample files from the Samples/ folder:',
    '   - In your file browser, navigate to the Samples/ subfolder',
    '   - Select ALL .wav files across all articulation subfolders',
    '   - Drag them into the Mapping Editor zone area',
    '   - When prompted, choose "Auto-Map" or just drop them — the script will remap',
    '',
    '7. Open the Script Editor:',
    '   - Click the "Script" tab (scroll icon) in the instrument header',
    '   - Click on an empty script slot (e.g., "Script 1")',
    '   - Click "Edit" to open the code editor',
    '',
    '8. Load the KSP script:',
    '   - Open the file: Scripts/' + instrumentName + '.ksp',
    '   - Select ALL the text (Ctrl+A / Cmd+A)',
    '   - Copy it (Ctrl+C / Cmd+C)',
    '   - Paste into the Kontakt Script Editor (Ctrl+V / Cmd+V)',
    '   - Click "Apply"',
    '',
    '9. The script will:',
    '   - Remap all zones to the correct MIDI notes',
    '   - Set velocity layer splits',
    '   - Create UI knobs for your configured controls',
    '   - Insert and configure effects',
    '   - You should see a confirmation message in the Kontakt status bar',
    '',
    '10. Save your instrument:',
    '    - File > Save As...',
    '    - Choose a location and name',
    '    - The instrument is now saved as a .nki file',
    '',
    '11. Play!',
    '    - Set up a MIDI track in your DAW pointing to this Kontakt instance',
    '    - Play notes on your MIDI controller or piano roll',
    '    - Your sampled instrument should respond to velocity and pitch',
    '',
    '',
    'INSTRUMENT DETAILS',
    '==================',
    '',
    'Name:           ' + instrumentName,
    'Samples:        ' + stats.totalSamples,
    'Articulations:  ' + stats.articulationList.join(', '),
    'Velocity Layers: ' + stats.maxVelocityLayers,
    'Round Robins:   ' + stats.maxRoundRobins,
    'Controls:       ' + (enabledCtrls.length > 0 ? enabledCtrls.join(', ') : 'None'),
    'Effects:        ' + (enabledFx.length > 0 ? enabledFx.join(', ') : 'None'),
    '',
    '',
    'SAMPLE MAP',
    '==========',
    '',
    'Filename'.padEnd(45) + 'Note'.padEnd(6) + 'Vel'.padEnd(5) + 'RR'.padEnd(5) + 'Articulation',
    '-'.repeat(80)
  ].concat(tableLines).concat([
    '',
    '',
    'TROUBLESHOOTING',
    '===============',
    '',
    '"No sound when I play"',
    '> Make sure you dragged the samples into the Mapping Editor, not just the Files tab',
    '> Check the Script Editor — click "Apply" again',
    '> Verify MIDI input is reaching Kontakt (check the MIDI indicator)',
    '',
    '"Wrong pitches"',
    '> The script remaps zones on Apply. Try clicking Apply again.',
    '> If zones still wrong, delete all zones, re-drag samples, re-apply script.',
    '',
    '"Script error on Apply"',
    '> Make sure you copied the ENTIRE script text (Ctrl+A before copying)',
    '> The script requires Kontakt 6 or newer. Kontakt 5 is not supported.',
    '> Check for stray characters at the beginning or end of the pasted text.',
    '',
    '',
    '================================================================================',
    '  Generated by SampleArchitect v1.0 | evenant.com',
    '================================================================================'
  ]);

  return guide.join('\n');
}
