/* ksp-gen.js — KSP script generator (CRITICAL PATH)                */
/* Generates UI knobs + control handlers + effects chain.            */
/* Zone mapping is handled by Kontakt's Mapping Editor (auto-map).   */
/*                                                                   */
/* All knob ranges: 0 to 1000000 (Kontakt native).                   */
/* No scaling math — values passed directly to set_engine_par().     */
/* Constants verified against KSP 6.0.2 Reference Manual.           */

var KNOB_VAR_NAMES = {
  volume: 'Volume',
  pan: 'Pan',
  attack: 'Attack',
  release: 'Release',
  tune: 'Tune',
  cutoff: 'Cutoff',
  resonance: 'Resonance',
  reverb: 'Reverb'
};

var KNOB_DEFAULTS = {
  volume:    { value: 750000, label: 'Vol' },
  pan:       { value: 500000, label: 'Pan' },
  attack:    { value: 0,      label: 'Atk' },
  release:   { value: 350000, label: 'Rel' },
  tune:      { value: 500000, label: 'Tune' },
  cutoff:    { value: 800000, label: 'Cut' },
  resonance: { value: 200000, label: 'Res' },
  reverb:    { value: 300000, label: 'Rvb' }
};

function generateKSP(samples, stats, config) {
  var lines = [];
  var mapped = samples.filter(function(s) { return s.parsed; });
  var instrumentName = stats.instrument || 'Instrument';
  var maxRR = stats.maxRoundRobins;

  var enabledControls = getEnabledControls();
  var enabledEffects = getEnabledEffects();

  // Skip EQ — $EFFECT_TYPE_PARA_EQ is inconsistent across Kontakt versions
  var activeEffects = enabledEffects.filter(function(e) { return e.key !== 'eq'; });

  // Layout constants
  var startX = 20;
  var knobY = 40;
  var spacing = 100;
  var maxPerRow = 6;
  var numRows = enabledControls.length > 0 ? Math.ceil(enabledControls.length / maxPerRow) : 0;
  var uiHeight = numRows <= 1 ? 250 : 330;

  lines.push('{ ' + instrumentName + ' - Generated by SampleArchitect }');
  lines.push('');
  lines.push('');
  lines.push('on init');

  // make_perfview MUST be the very first command after on init
  lines.push('  make_perfview');
  lines.push('  set_script_title("' + instrumentName + ' - SampleArchitect")');
  lines.push('  message("")');
  lines.push('  set_ui_height_px(' + uiHeight + ')');
  lines.push('  set_ui_color(ff0a0a0bh)');

  // Title label
  lines.push('');
  lines.push('  { Title Label }');
  lines.push('  declare ui_label $title (4, 1)');
  lines.push('  set_text($title, "' + instrumentName + '")');
  lines.push('  set_control_par(get_ui_id($title), $CONTROL_PAR_POS_X, 20)');
  lines.push('  set_control_par(get_ui_id($title), $CONTROL_PAR_POS_Y, 2)');
  lines.push('  set_control_par(get_ui_id($title), $CONTROL_PAR_TEXT_ALIGNMENT, 0)');
  lines.push('  set_control_par(get_ui_id($title), $CONTROL_PAR_FONT_TYPE, 1)');

  // UI Controls — declare each knob and position it immediately
  var knobNames = [];
  if (enabledControls.length > 0) {
    lines.push('');
    lines.push('  { UI Controls }');
  }

  enabledControls.forEach(function(item, index) {
    var key = item.key;
    var varName = KNOB_VAR_NAMES[key];
    var defaults = KNOB_DEFAULTS[key];
    knobNames.push(varName);

    var row = Math.floor(index / maxPerRow);
    var col = index % maxPerRow;
    var x = startX + (col * spacing);
    var y = knobY + (row * 80);

    lines.push('');
    lines.push('  declare ui_knob $' + varName + ' (0, 1000000, 1)');
    lines.push('  $' + varName + ' := ' + defaults.value);
    lines.push('  set_knob_defval($' + varName + ', ' + defaults.value + ')');
    lines.push('  set_knob_label($' + varName + ', "' + defaults.label + '")');
    lines.push('  make_persistent($' + varName + ')');
    lines.push('  set_control_par(get_ui_id($' + varName + '), $CONTROL_PAR_POS_X, ' + x + ')');
    lines.push('  set_control_par(get_ui_id($' + varName + '), $CONTROL_PAR_POS_Y, ' + y + ')');
  });

  // Effects Chain (verified working in Kontakt 6)
  if (activeEffects.length > 0) {
    lines.push('');
    lines.push('  { Effects Chain }');

    activeEffects.forEach(function(item) {
      if (item.key === 'filter') {
        lines.push('  set_engine_par($ENGINE_PAR_EFFECT_TYPE, $EFFECT_TYPE_FILTER, 0, 0, -1)');
      } else if (item.key === 'reverb') {
        lines.push('  set_engine_par($ENGINE_PAR_EFFECT_TYPE, $EFFECT_TYPE_REVERB, -1, 0, 1)');
      } else if (item.key === 'delay') {
        lines.push('  set_engine_par($ENGINE_PAR_EFFECT_TYPE, $EFFECT_TYPE_DELAY, -1, 1, 1)');
      }
    });
  }

  // Round robin counter declaration (inside on init)
  if (maxRR > 1) {
    lines.push('');
    lines.push('  { Round Robin }');
    lines.push('  declare $rr_counter');
    lines.push('  $rr_counter := 0');
  }

  lines.push('end on');

  // UI Control Handlers — values passed directly, no scaling
  if (enabledControls.length > 0) {
    lines.push('');

    enabledControls.forEach(function(item) {
      var key = item.key;
      var varName = KNOB_VAR_NAMES[key];
      lines.push('');

      if (key === 'volume') {
        lines.push('on ui_control ($' + varName + ')');
        lines.push('  set_engine_par($ENGINE_PAR_VOLUME, $' + varName + ', -1, -1, -1)');
        lines.push('end on');
      } else if (key === 'pan') {
        lines.push('on ui_control ($' + varName + ')');
        lines.push('  set_engine_par($ENGINE_PAR_PAN, $' + varName + ', -1, -1, -1)');
        lines.push('end on');
      } else if (key === 'attack') {
        lines.push('on ui_control ($' + varName + ')');
        lines.push('  set_engine_par($ENGINE_PAR_ATTACK, $' + varName + ', -1, -1, -1)');
        lines.push('end on');
      } else if (key === 'release') {
        lines.push('on ui_control ($' + varName + ')');
        lines.push('  set_engine_par($ENGINE_PAR_RELEASE, $' + varName + ', -1, -1, -1)');
        lines.push('end on');
      } else if (key === 'tune') {
        lines.push('on ui_control ($' + varName + ')');
        lines.push('  set_engine_par($ENGINE_PAR_TUNE, $' + varName + ', -1, -1, -1)');
        lines.push('end on');
      } else if (key === 'cutoff') {
        lines.push('on ui_control ($' + varName + ')');
        lines.push('  set_engine_par($ENGINE_PAR_CUTOFF, $' + varName + ', 0, 0, -1)');
        lines.push('end on');
      } else if (key === 'resonance') {
        lines.push('on ui_control ($' + varName + ')');
        lines.push('  set_engine_par($ENGINE_PAR_RESONANCE, $' + varName + ', 0, 0, -1)');
        lines.push('end on');
      } else if (key === 'reverb') {
        lines.push('on ui_control ($' + varName + ')');
        lines.push('  set_engine_par($ENGINE_PAR_INSERT_EFFECT_OUTPUT_GAIN, $' + varName + ', -1, 0, 1)');
        lines.push('end on');
      }
    });
  }

  // Round Robin Cycling
  if (maxRR > 1) {
    lines.push('');
    lines.push('');
    lines.push('on note');
    lines.push('  $rr_counter := ($rr_counter + 1) mod ' + maxRR);
    lines.push('  ');
    lines.push('  declare $g');
    lines.push('  $g := 0');
    lines.push('  while ($g < ' + maxRR + ')');
    lines.push('    if ($g = $rr_counter)');
    lines.push('      allow_group($g)');
    lines.push('    else');
    lines.push('      disallow_group($g)');
    lines.push('    end if');
    lines.push('    $g := $g + 1');
    lines.push('  end while');
    lines.push('end on');
  }

  lines.push('');

  return lines.join('\n');
}
