/* ksp-gen.js — KSP script generator (CRITICAL PATH)                */
/* Generates UI sliders (with knob skin) + control handlers + FX.   */
/* Zone mapping is handled by Kontakt's Mapping Editor (auto-map).  */
/*                                                                   */
/* All slider ranges: 0 to 1000000 (Kontakt native).                */
/* No scaling math — values passed directly to set_engine_par().    */
/* Constants verified against KSP 6.0.2 Reference Manual.          */
/* Uses ui_slider + $CONTROL_PAR_PICTURE for custom knob graphics.  */

var KNOB_VAR_NAMES = {
  volume: 'Volume',
  pan: 'Pan',
  attack: 'Attack',
  release: 'Release',
  tune: 'Tune',
  cutoff: 'Cutoff',
  resonance: 'Resonance',
  reverb: 'Reverb'
};

/* Label text for wallpaper baking AND companion ui_label controls */
var KNOB_FULL_LABELS = {
  volume: 'VOLUME',
  pan: 'PAN',
  attack: 'ATTACK',
  release: 'RELEASE',
  tune: 'TUNE',
  cutoff: 'CUTOFF',
  resonance: 'RESONANCE',
  reverb: 'REVERB'
};

/* Short label variable names for KSP (must be unique, short for Kontakt) */
var KNOB_LABEL_VARS = {
  volume: 'lVol',
  pan: 'lPan',
  attack: 'lAtk',
  release: 'lRel',
  tune: 'lTun',
  cutoff: 'lCut',
  resonance: 'lRes',
  reverb: 'lRev'
};

/* Convert ARGB hex color to signed 32-bit decimal for KSP */
function colorToKSP(hex) {
  return hex > 0x7FFFFFFF ? hex - 0x100000000 : hex;
}

var UI_COLOR_DARK = colorToKSP(0xFF0A0A0B); // -16119285

var KNOB_DEFAULTS = {
  volume:    { value: 750000 },
  pan:       { value: 500000 },
  attack:    { value: 0 },
  release:   { value: 350000 },
  tune:      { value: 500000 },
  cutoff:    { value: 800000 },
  resonance: { value: 200000 },
  reverb:    { value: 300000 }
};

function generateKSP(samples, stats, config) {
  var lines = [];
  var mapped = samples.filter(function(s) { return s.parsed; });
  var instrumentName = stats.instrument || 'Instrument';
  var maxRR = stats.maxRoundRobins;

  var enabledControls = getEnabledControls();
  var enabledEffects = getEnabledEffects();

  // Skip EQ — $EFFECT_TYPE_PARA_EQ is inconsistent across Kontakt versions
  var activeEffects = enabledEffects.filter(function(e) { return e.key !== 'eq'; });

  // Layout constants — 4x2 grid of sliders with knob skin
  var startX = 30;
  var knobY = 200;
  var spacing = 100;
  var maxPerRow = 4;
  var numRows = enabledControls.length > 0 ? Math.ceil(enabledControls.length / maxPerRow) : 0;
  var uiHeight = numRows <= 1 ? 320 : 430;

  lines.push('{ ' + instrumentName + ' - Generated by SampleArchitect }');
  lines.push('');
  lines.push('');
  lines.push('on init');

  // make_perfview MUST be the very first command after on init
  lines.push('  make_perfview');
  lines.push('  set_script_title("' + instrumentName + ' - SampleArchitect")');
  lines.push('  message("")');
  lines.push('  set_ui_height_px(' + uiHeight + ')');

  // Wallpaper replaces set_ui_color — keep as commented fallback
  lines.push('  { set_ui_color(' + UI_COLOR_DARK + ') }');

  // Wallpaper reference via resource container
  lines.push('');
  lines.push('  { Wallpaper }');
  lines.push('  set_control_par_str($INST_WALLPAPER_ID, $CONTROL_PAR_PICTURE, "wallpaper")');

  // UI Controls — declare each slider with knob skin + companion ui_label
  if (enabledControls.length > 0) {
    lines.push('');
    lines.push('  { UI Controls }');
  }

  enabledControls.forEach(function(item, index) {
    var key = item.key;
    var varName = KNOB_VAR_NAMES[key];
    var labelVar = KNOB_LABEL_VARS[key];
    var fullLabel = KNOB_FULL_LABELS[key];
    var defaults = KNOB_DEFAULTS[key];

    var row = Math.floor(index / maxPerRow);
    var col = index % maxPerRow;
    var x = startX + (col * spacing);
    var y = knobY + (row * 110);
    var labelX = x - 13;
    var labelY = y + 58;

    // Slider declaration
    lines.push('');
    lines.push('  { ' + varName + ' }');
    lines.push('  declare ui_slider $' + varName + ' (0, 1000000)');
    lines.push('  $' + varName + ' := ' + defaults.value);
    lines.push('  make_persistent($' + varName + ')');
    lines.push('  set_control_par(get_ui_id($' + varName + '), $CONTROL_PAR_POS_X, ' + x + ')');
    lines.push('  set_control_par(get_ui_id($' + varName + '), $CONTROL_PAR_POS_Y, ' + y + ')');
    lines.push('  set_control_par(get_ui_id($' + varName + '), $CONTROL_PAR_WIDTH, 54)');
    lines.push('  set_control_par(get_ui_id($' + varName + '), $CONTROL_PAR_HEIGHT, 54)');
    lines.push('  set_control_par(get_ui_id($' + varName + '), $CONTROL_PAR_MOUSE_BEHAVIOUR, -2000)');
    lines.push('  set_control_par(get_ui_id($' + varName + '), $CONTROL_PAR_DEFAULT_VALUE, ' + defaults.value + ')');
    lines.push('  set_control_par_str(get_ui_id($' + varName + '), $CONTROL_PAR_PICTURE, "knob")');

    // Companion label
    lines.push('  declare ui_label $' + labelVar + ' (1, 1)');
    lines.push('  set_text($' + labelVar + ', "' + fullLabel + '")');
    lines.push('  set_control_par(get_ui_id($' + labelVar + '), $CONTROL_PAR_POS_X, ' + labelX + ')');
    lines.push('  set_control_par(get_ui_id($' + labelVar + '), $CONTROL_PAR_POS_Y, ' + labelY + ')');
    lines.push('  set_control_par(get_ui_id($' + labelVar + '), $CONTROL_PAR_WIDTH, 80)');
    lines.push('  set_control_par(get_ui_id($' + labelVar + '), $CONTROL_PAR_HEIGHT, 14)');
    lines.push('  set_control_par(get_ui_id($' + labelVar + '), $CONTROL_PAR_TEXT_ALIGNMENT, 1)');
    lines.push('  set_control_par(get_ui_id($' + labelVar + '), $CONTROL_PAR_FONT_TYPE, 3)');
    lines.push('  hide_part($' + labelVar + ', $HIDE_PART_BG)');
  });

  // Apply init defaults for group-level params (envelope params need group 0)
  enabledControls.forEach(function(item) {
    var key = item.key;
    var varName = KNOB_VAR_NAMES[key];
    if (key === 'attack') {
      lines.push('  set_engine_par($ENGINE_PAR_ATTACK, $' + varName + ', 0, -1, -1)');
    } else if (key === 'release') {
      lines.push('  set_engine_par($ENGINE_PAR_RELEASE, $' + varName + ', 0, -1, -1)');
    }
  });

  // Effects Chain (verified working in Kontakt 6)
  if (activeEffects.length > 0) {
    lines.push('');
    lines.push('  { Effects Chain }');

    activeEffects.forEach(function(item) {
      if (item.key === 'filter') {
        lines.push('  set_engine_par($ENGINE_PAR_EFFECT_TYPE, $EFFECT_TYPE_FILTER, 0, 0, -1)');
      } else if (item.key === 'reverb') {
        lines.push('  set_engine_par($ENGINE_PAR_EFFECT_TYPE, $EFFECT_TYPE_REVERB, -1, 0, 1)');
      } else if (item.key === 'delay') {
        lines.push('  set_engine_par($ENGINE_PAR_EFFECT_TYPE, $EFFECT_TYPE_DELAY, -1, 1, 1)');
      }
    });
  }

  // Round robin counter declaration (inside on init)
  if (maxRR > 1) {
    lines.push('');
    lines.push('  { Round Robin }');
    lines.push('  declare $rr_counter');
    lines.push('  $rr_counter := 0');
  }

  lines.push('end on');

  // UI Control Handlers — values passed directly, no scaling
  if (enabledControls.length > 0) {
    lines.push('');

    enabledControls.forEach(function(item) {
      var key = item.key;
      var varName = KNOB_VAR_NAMES[key];
      lines.push('');

      if (key === 'volume') {
        lines.push('on ui_control ($' + varName + ')');
        lines.push('  set_engine_par($ENGINE_PAR_VOLUME, $' + varName + ', -1, -1, -1)');
        lines.push('end on');
      } else if (key === 'pan') {
        lines.push('on ui_control ($' + varName + ')');
        lines.push('  set_engine_par($ENGINE_PAR_PAN, $' + varName + ', -1, -1, -1)');
        lines.push('end on');
      } else if (key === 'attack') {
        lines.push('on ui_control ($' + varName + ')');
        lines.push('  set_engine_par($ENGINE_PAR_ATTACK, $' + varName + ', 0, -1, -1)');
        lines.push('end on');
      } else if (key === 'release') {
        lines.push('on ui_control ($' + varName + ')');
        lines.push('  set_engine_par($ENGINE_PAR_RELEASE, $' + varName + ', 0, -1, -1)');
        lines.push('end on');
      } else if (key === 'tune') {
        lines.push('on ui_control ($' + varName + ')');
        lines.push('  set_engine_par($ENGINE_PAR_TUNE, $' + varName + ', -1, -1, -1)');
        lines.push('end on');
      } else if (key === 'cutoff') {
        lines.push('on ui_control ($' + varName + ')');
        lines.push('  set_engine_par($ENGINE_PAR_CUTOFF, $' + varName + ', 0, 0, -1)');
        lines.push('end on');
      } else if (key === 'resonance') {
        lines.push('on ui_control ($' + varName + ')');
        lines.push('  set_engine_par($ENGINE_PAR_RESONANCE, $' + varName + ', 0, 0, -1)');
        lines.push('end on');
      } else if (key === 'reverb') {
        lines.push('on ui_control ($' + varName + ')');
        lines.push('  set_engine_par($ENGINE_PAR_INSERT_EFFECT_OUTPUT_GAIN, $' + varName + ', -1, 0, 1)');
        lines.push('end on');
      }
    });
  }

  // Round Robin Cycling
  if (maxRR > 1) {
    lines.push('');
    lines.push('');
    lines.push('on note');
    lines.push('  $rr_counter := ($rr_counter + 1) mod ' + maxRR);
    lines.push('  ');
    lines.push('  declare $g');
    lines.push('  $g := 0');
    lines.push('  while ($g < ' + maxRR + ')');
    lines.push('    if ($g = $rr_counter)');
    lines.push('      allow_group($g)');
    lines.push('    else');
    lines.push('      disallow_group($g)');
    lines.push('    end if');
    lines.push('    $g := $g + 1');
    lines.push('  end while');
    lines.push('end on');
  }

  lines.push('');

  return lines.join('\n');
}
