/* ksp-gen.js — KSP script generator (CRITICAL PATH) */

function generateKSP(samples, stats, config) {
  var lines = [];
  var mapped = samples.filter(function(s) { return s.parsed; });
  var instrumentName = stats.instrument || 'Instrument';
  var maxRR = stats.maxRoundRobins;
  var numGroups = maxRR;

  lines.push('{ ' + instrumentName + ' - Generated by SampleArchitect }');
  lines.push('');
  lines.push('');
  lines.push('on init');
  lines.push('  set_script_title("' + instrumentName + ' - SampleArchitect")');
  lines.push('  ');
  lines.push('  { -- Instrument Info -- }');
  lines.push('  message("Loading ' + instrumentName + ' | ' + mapped.length + ' samples | SampleArchitect")');
  lines.push('  ');

  // UI Controls
  lines.push('  { -- UI Controls -- }');

  var enabledControls = getEnabledControls();
  enabledControls.forEach(function(item) {
    var key = item.key;
    var cfg = item.config;
    var scaledDefault = scaleDefault(key);

    lines.push('  ');

    if (key === 'volume') {
      lines.push('  declare ui_knob $Volume (0, 1000000, 1)');
      lines.push('  $Volume := ' + scaledDefault);
      lines.push('  set_knob_defval($Volume, $Volume)');
      lines.push('  set_knob_unit($Volume, $KNOB_UNIT_NONE)');
      lines.push('  set_knob_label($Volume, "Vol")');
      lines.push('  make_persistent($Volume)');
    } else if (key === 'pan') {
      lines.push('  declare ui_knob $Pan (-1000, 1000, 1)');
      lines.push('  $Pan := ' + scaledDefault);
      lines.push('  set_knob_defval($Pan, ' + scaledDefault + ')');
      lines.push('  set_knob_unit($Pan, $KNOB_UNIT_NONE)');
      lines.push('  set_knob_label($Pan, "Pan")');
      lines.push('  make_persistent($Pan)');
    } else if (key === 'attack') {
      lines.push('  declare ui_knob $Attack (0, 1000000, 1)');
      lines.push('  $Attack := ' + scaledDefault);
      lines.push('  set_knob_defval($Attack, $Attack)');
      lines.push('  set_knob_unit($Attack, $KNOB_UNIT_NONE)');
      lines.push('  set_knob_label($Attack, "Atk")');
      lines.push('  make_persistent($Attack)');
    } else if (key === 'release') {
      lines.push('  declare ui_knob $Release (0, 1000000, 1)');
      lines.push('  $Release := ' + scaledDefault);
      lines.push('  set_knob_defval($Release, $Release)');
      lines.push('  set_knob_unit($Release, $KNOB_UNIT_NONE)');
      lines.push('  set_knob_label($Release, "Rel")');
      lines.push('  make_persistent($Release)');
    } else if (key === 'tune') {
      lines.push('  declare ui_knob $Tune (-36000, 36000, 1)');
      lines.push('  $Tune := ' + scaledDefault);
      lines.push('  set_knob_defval($Tune, ' + scaledDefault + ')');
      lines.push('  set_knob_unit($Tune, $KNOB_UNIT_NONE)');
      lines.push('  set_knob_label($Tune, "Tune")');
      lines.push('  make_persistent($Tune)');
    } else if (key === 'cutoff') {
      lines.push('  declare ui_knob $Cutoff (0, 1000000, 1)');
      lines.push('  $Cutoff := ' + scaledDefault);
      lines.push('  set_knob_defval($Cutoff, $Cutoff)');
      lines.push('  set_knob_unit($Cutoff, $KNOB_UNIT_NONE)');
      lines.push('  set_knob_label($Cutoff, "Cut")');
      lines.push('  make_persistent($Cutoff)');
    } else if (key === 'resonance') {
      lines.push('  declare ui_knob $Resonance (0, 1000000, 1)');
      lines.push('  $Resonance := ' + scaledDefault);
      lines.push('  set_knob_defval($Resonance, $Resonance)');
      lines.push('  set_knob_unit($Resonance, $KNOB_UNIT_NONE)');
      lines.push('  set_knob_label($Resonance, "Res")');
      lines.push('  make_persistent($Resonance)');
    } else if (key === 'reverb') {
      lines.push('  declare ui_knob $ReverbSend (0, 1000000, 1)');
      lines.push('  $ReverbSend := ' + scaledDefault);
      lines.push('  set_knob_defval($ReverbSend, $ReverbSend)');
      lines.push('  set_knob_unit($ReverbSend, $KNOB_UNIT_NONE)');
      lines.push('  set_knob_label($ReverbSend, "Rvb")');
      lines.push('  make_persistent($ReverbSend)');
    }
  });

  lines.push('  ');
  lines.push('  ');

  // Zone Mapping
  lines.push('  { -- Zone Mapping -- }');
  lines.push('  declare $i');
  lines.push('  declare $zone_id');
  lines.push('  declare @zone_name');
  lines.push('  declare $num_zones');
  lines.push('  ');
  lines.push('  $num_zones := ' + mapped.length);
  lines.push('  $i := 0');
  lines.push('  ');
  lines.push('  while ($i < $num_zones)');
  lines.push('    $zone_id := get_zone_id($i)');
  lines.push('    @zone_name := zone_get_sample_name($zone_id)');
  lines.push('    ');

  mapped.forEach(function(s) {
    var zoneName = s.filename.replace('.wav', '').replace('.WAV', '');
    var group = (s.roundRobin || 1) - 1;

    lines.push('    if (@zone_name = "' + zoneName + '")');
    lines.push('      set_zone_par($zone_id, $ZONE_PAR_ROOT_KEY, ' + s.rootKey + ')');
    lines.push('      set_zone_par($zone_id, $ZONE_PAR_LOW_KEY, ' + s.lowKey + ')');
    lines.push('      set_zone_par($zone_id, $ZONE_PAR_HIGH_KEY, ' + s.highKey + ')');
    lines.push('      set_zone_par($zone_id, $ZONE_PAR_LOW_VELO, ' + s.velLow + ')');
    lines.push('      set_zone_par($zone_id, $ZONE_PAR_HIGH_VELO, ' + s.velHigh + ')');
    lines.push('      set_zone_par($zone_id, $ZONE_PAR_GROUP, ' + group + ')');
    lines.push('    end if');
    lines.push('    ');
  });

  lines.push('    $i := $i + 1');
  lines.push('  end while');
  lines.push('  ');

  // Effects Chain
  var enabledEffects = getEnabledEffects();
  if (enabledEffects.length > 0) {
    lines.push('  ');
    lines.push('  { -- Effects Chain -- }');

    enabledEffects.forEach(function(item) {
      var key = item.key;
      if (key === 'filter') {
        lines.push('  set_engine_par($ENGINE_PAR_EFFECT_TYPE, $EFFECT_TYPE_FILTER, 0, 0, -1)');
        lines.push('  set_engine_par($ENGINE_PAR_EFFECT_SUBTYPE, 1, 0, 0, -1)');
      } else if (key === 'reverb') {
        lines.push('  set_engine_par($ENGINE_PAR_EFFECT_TYPE, $EFFECT_TYPE_REVERB, -1, 0, 1)');
      } else if (key === 'delay') {
        lines.push('  set_engine_par($ENGINE_PAR_EFFECT_TYPE, $EFFECT_TYPE_DELAY, -1, 1, 1)');
      }
      // EQ skipped for MVP as noted in reference
    });
  }

  lines.push('  ');
  lines.push('end on');
  lines.push('');

  // UI Control Handlers
  lines.push('');
  lines.push('{ -- UI Control Handlers -- }');

  enabledControls.forEach(function(item) {
    var key = item.key;
    lines.push('');
    if (key === 'volume') {
      lines.push('on ui_control ($Volume)');
      lines.push('  set_engine_par($ENGINE_PAR_VOLUME, $Volume * 630 / 1000000, -1, -1, -1)');
      lines.push('end on');
    } else if (key === 'pan') {
      lines.push('on ui_control ($Pan)');
      lines.push('  set_engine_par($ENGINE_PAR_PAN, $Pan, -1, -1, -1)');
      lines.push('end on');
    } else if (key === 'attack') {
      lines.push('on ui_control ($Attack)');
      lines.push('  set_engine_par($ENGINE_PAR_ATTACK, $Attack, -1, -1, -1)');
      lines.push('end on');
    } else if (key === 'release') {
      lines.push('on ui_control ($Release)');
      lines.push('  set_engine_par($ENGINE_PAR_RELEASE, $Release, -1, -1, -1)');
      lines.push('end on');
    } else if (key === 'tune') {
      lines.push('on ui_control ($Tune)');
      lines.push('  set_engine_par($ENGINE_PAR_TUNE, $Tune, -1, -1, -1)');
      lines.push('end on');
    } else if (key === 'cutoff') {
      lines.push('on ui_control ($Cutoff)');
      lines.push('  set_engine_par($ENGINE_PAR_CUTOFF, $Cutoff, 0, 0, -1)');
      lines.push('end on');
    } else if (key === 'resonance') {
      lines.push('on ui_control ($Resonance)');
      lines.push('  set_engine_par($ENGINE_PAR_RESONANCE, $Resonance, 0, 0, -1)');
      lines.push('end on');
    } else if (key === 'reverb') {
      lines.push('on ui_control ($ReverbSend)');
      lines.push('  set_engine_par($ENGINE_PAR_SEND_EFFECT_0_LEVEL, $ReverbSend * 630 / 1000000, -1, -1, -1)');
      lines.push('end on');
    }
  });

  // Round Robin Cycling
  if (maxRR > 1) {
    lines.push('');
    lines.push('');
    lines.push('{ -- Round Robin Cycling -- }');
    lines.push('');
    lines.push('on note');
    lines.push('  declare $rr_counter');
    lines.push('  $rr_counter := ($rr_counter + 1) mod ' + maxRR);
    lines.push('  ');
    lines.push('  declare $g');
    lines.push('  $g := 0');
    lines.push('  while ($g < ' + numGroups + ')');
    lines.push('    if ($g = $rr_counter)');
    lines.push('      allow_group($g)');
    lines.push('    else');
    lines.push('      disallow_group($g)');
    lines.push('    end if');
    lines.push('    $g := $g + 1');
    lines.push('  end while');
    lines.push('end on');
  }

  lines.push('');

  return lines.join('\n');
}
